name: Copy To Branches
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          key: main
          # By default it will copy dev container information to all branches which we don't want
          # And I want .gitignore to be copied over
          files: LICENSE NOTICE README.md CONTRIBUTING.md .gitignore .github/CODEOWNERS .github/ISSUE_TEMPLATE.MD .github/PULL_REQUEST_TEMPLATE.MD .github/workflows/main.yml